server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://localhost:1433;databaseName=books;integratedSecurity=true;\
          encrypt=false;trustServerCertificate=true"
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: true
  cache:
    type: redis

logging:
  level:
    org:
      hibernate: warn